# -*- coding: utf-8 -*-
"""LVADUSR94_regression.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1M1YrV9fvmKRF0G_-mZHWpyph75BJ2A95
"""

import pandas as pd
import numpy as np

data = pd.read_csv("/content/auto-mpg.csv")
data.isnull().sum()

data.head()

from sklearn.impute import SimpleImputer

imp = SimpleImputer(strategy = "mean")
data['displacement'] = imp.fit_transform(data[['displacement']])
data['acceleration'] = imp.fit_transform(data[['acceleration']])
imp = SimpleImputer(strategy = "most_frequent")
data['horsepower'] = imp.fit_transform(data[['horsepower']])

data.duplicated().sum()

import seaborn as sns

sns.heatmap(data.corr(),annot=True)

data.head(3)

from sklearn.preprocessing import LabelEncoder
Le = LabelEncoder()
data["horsepower"] = Le.fit_transform(data["horsepower"])

from sklearn.model_selection import train_test_split

X = data.drop(["mpg","car name"],axis="columns")
y = data["mpg"]
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=42)

from sklearn.linear_model import LinearRegression

clf = LinearRegression()
model = clf.fit(X_train,y_train)
y_pred = clf.predict(X_test)

from sklearn.metrics import mean_squared_error,mean_absolute_error,r2_score

mse = mean_squared_error(y_pred,y_test)
mae = mean_absolute_error(y_pred,y_test)
rmse = np.sqrt(mse)
r2 = r2_score(y_pred,y_test)
print("MSE:\n",mse)
print("\nMAE:\n",mae)
print("\nRMSE:\n",rmse)
print("\nR2:\n",r2)