# -*- coding: utf-8 -*-
"""LVADAUSR94_anamolies.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/19IrgASFOczYAEYOA0iHC0tll0Y-6ODRg
"""

import pandas as pd
import numpy as np

data = pd.read_csv("/content/social_network.csv")
data.isnull().sum()

data.duplicated().sum()

import matplotlib.pyplot as plt
import seaborn as sns
plt.figure(figsize=(18, 5))
plt.subplot(1, 3, 1)
sns.histplot(data=data, x='login_activity', kde=True)
plt.subplot(1, 3, 2)
sns.histplot(data=data, x='posting_activity', kde=True)
plt.subplot(1, 3, 3)
sns.histplot(data=data, x='social_connections', kde=True)

plt.tight_layout()
plt.show()

cols = ['login_activity','posting_activity','social_connections']
X =data[cols]
from sklearn.ensemble import IsolationForest
model = IsolationForest(n_estimators=100, random_state=42)
predictions = model.fit_predict(X)

data['score'] = model.decision_function(X)
data['anomaly'] = predictions
data['anomaly'] = data['anomaly'].apply(lambda x: 1 if x == -1 else 0)

print(data.head())
print(data['anomaly'].value_counts())

plt.figure(figsize=(10, 6))
sns.histplot(data=data, x='score', hue='anomaly', element='step', palette='viridis')
plt.title('Distribution of Anomaly Scores')
plt.show()