# -*- coding: utf-8 -*-
"""internal_1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1LXb8esobBLnXjEIjae1te0PAetigKDrM
"""

# LAB 1
# #1
length = int(input("enter length:  "))
width = int(input("enter width:  "))
print("area is ", length*width)

#2
weight = float(input("enter your weight in kgs:"))
height = float(input("enter your height in cms:"))
print("your bmi is  ",round(weight/(pow(height*0.01,2)),2))

#3
students = {}
name  = input("enter students name: ")
while(name):
  score = int(input("enter score: "))
  students.update({name:score})
  name  = input("enter students name or press enter to exit ")

print(students)

#4
age = input("enter your age:")
while(age):
  if age < '18':
    print("minor")
  elif age>'18' and age < '60':
    print("adult")
  else :
    print("senior")
  age = input("enter your age or press enter to exit")

#5
for i in range(50):
  if i%2 == 0:
    print(i, end= " ")

#6
users = {}

name = input("enter username: ")
pwd = input("set your password: ")
users.update({name:pwd})
try:
  name  = input("enter username: ")
  pwd = input("enter your password: ")
  while(pwd != users[name]):
    pwd = input("enter your password: ")
except:
  print("key not found")

#7
data = list(map(int,input("give a list of numbers").split()))

l = len(data)
sum = 0
for i in data:
  sum += i
print("average is :" , sum/l)

#8
data = input("enter a string")
vowel_c = 0
for i in data:
  if i in ['A','E','I','O','U'] or i in ['a','e','i','o','u'] :
    vowel_c += 1
print("number of vowels in the string are: ",vowel_c)

#9
from datetime import datetime

now = datetime.now()
print(now)

#10

a = input("enter values: ").split()
while(a):
  try:
    print(int(a[0])+int(a[1]))
  except:
    print("enter numeric values")
  a = input("enter values or press enter to exit ").split()

#11
try:
  a = int(input())
except:
  print("enter integer values")

#12
a = list(map(int,input("enter 2 numbers:").split()))

try:
  print(a[0]/a[1])
except:
  print("cannot divide by zero, try again")

#13

with open("/content/sample_data/python",'w') as file:
  file.write("Hello, Python!")

#14
with open("/content/sample_data/python",'r') as file:
  x = file.read()
print(x)

#15

with open("/content/sample_data/python",'a') as file:
  file.write("\ninternal assessment 1")
with open("/content/sample_data/python",'r') as file:
  x = file.read()
print(x)