# -*- coding: utf-8 -*-
"""LVADSUSR94-LAKSHMI_IA2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/13lWSyQJZG7x_TfD59TQcoUJAXXeOPNu4
"""

#Q1
import numpy as np
rgb_image = np.array([[[255,0,0],[0,255,0],[0,0,255]],
                      [[255,255,0],[255,0,255],[0,255,255]],
                      [[127,127,127],[200,200,200],[50,50,50]]])

gray_scale = np.array([0.2989,0.5870,0.1140])
converted = rgb_image @ gray_scale
print(converted)

#q2
data = np.array([[1,2,3],[4,5,6],[4,8,2]])
a = np.mean(data,axis=1)
normalized = data/a
print(normalized)

#Q3
data = np.array([[[1,2],[2,3]],[[4,7],[8,9]]])
a  = data[0].flatten()
b  = data[1].flatten()
data = np.array([[a,b]])
data = data.reshape(2,4)
data

#Q4
scores = np.array([[1,5,3,2,5],[2,4,2,1,5],[4,5,4,5,3]])
improvement = (scores[0][-1]-scores[0][0])/scores[0][0]
improvement ={}
for i in range(len(scores)):
  improvement.update({i:(scores[i][-1]-scores[i][0])/scores[i][0]})
improvement

#Q5
import pandas as pd

students = np.array([[20,30,40,70],[30,30,50,40],[60,40,30,60]])
for i in students:
  sum = 0
  for j in i[-3:]:
    if(j>0):
      sum += j
  print("average of last 3 subjects for student",i, "=" ,round(sum/3,3))

#Q6
def adjustments(a,b):
  return a + b

month_temp = np.array([[30,29,30,28,25,40,22,10,30,27,26,18],[30,25,30,28,25,38,17,10,30,27,26,18],[30,38,30,25,25,40,22,10,25,27,26,18]])
#print(month_temp)
adjustments_temp = np.array([2,3,1,2,5,2,7,1,2,0,2,4])
print(adjustments(month_temp,adjustments_temp))

#Q7
data = {'Name':['Alice','Bob','Charlie','David','Eve','Frank','Grace'],
        'Age': [25,30,35,40,45,50,55],
        'City':['New York','Los Angeles','Chicago','Houston','Phoenix','Miami'
        ,'Boston'],
        'Department':['HR','IT','finance','Marketing','sales','IT','HR']
        }
data = pd.DataFrame(data)
condition = data['Age']< 45
c = data['Department'] != 'HR'
fc = c & condition
print("required employees : \n", data[fc])

#Q8
data = {'Product':['apples','bananas','Cherries','Dates','Elderberries','Flour','Grapes'],
        'Category':['Fruit','Fruit','Fruit','Fruit','Fruit','Bakery','Fruit'],
        'Price':[1.20,0.50,3.00,2.50,4.00,1.50,2.00],
        'Promotion':[True,False,True,True,False,True,False]}
data = pd.DataFrame(data)
average_price = data.Price.mean()
c1 = data.Price > average_price
c2 = data.Category == 'Fruit'
c3 = data.Promotion == False
data = data[c1&c2&c3]
print(data)

#Q9
e_d = {'Employee':['Alice','Bob','Charlies','David'],
       'Dept':['HR','IT','finance','IT'],
       'Manager':['John','Rachel','Emily','Rachel']}
p_d = {'Employee':['Alice','Charlie','Eve'],
       'Project':['p1','p2','p3']}

d1 = pd.DataFrame(e_d)
d2 = pd.DataFrame(p_d)
merged = pd.merge(d1,d2,on='Employee',how ='outer')
print(merged)

#Q10
data = {'Dept':['Electronics','Electronics','Clothing','Clothing','Home Goods'],
        'Salesperson':['Alice','bob','Charlies','David','EVe'],
        'Sales': [70000,50000,30000,40000,60000]}
data = pd.DataFrame(data)
d1 = data.groupby('Dept')
print(data.groupby('Salesperson').mean())